import type { AnimalListItem } from './types'

export const LAND_ANIMALS: AnimalListItem[] = [
  { slug: 'lion', name_ko: '사자', name_en: 'Lion', wiki_title: 'Lion' },
  { slug: 'tiger', name_ko: '호랑이', name_en: 'Tiger', wiki_title: 'Tiger' },
  { slug: 'elephant', name_ko: '코끼리', name_en: 'Elephant', wiki_title: 'Elephant' },
  { slug: 'giraffe', name_ko: '기린', name_en: 'Giraffe', wiki_title: 'Giraffe' },
  { slug: 'zebra', name_ko: '얼룩말', name_en: 'Zebra', wiki_title: 'Zebra' },
  { slug: 'cheetah', name_ko: '치타', name_en: 'Cheetah', wiki_title: 'Cheetah' },
  { slug: 'leopard', name_ko: '표범', name_en: 'Leopard', wiki_title: 'Leopard' },
  { slug: 'rhinoceros', name_ko: '코뿔소', name_en: 'Rhinoceros', wiki_title: 'Rhinoceros' },
  { slug: 'hippopotamus', name_ko: '하마', name_en: 'Hippopotamus', wiki_title: 'Hippopotamus' },
  { slug: 'gorilla', name_ko: '고릴라', name_en: 'Gorilla', wiki_title: 'Gorilla' },
  { slug: 'chimpanzee', name_ko: '침팬지', name_en: 'Chimpanzee', wiki_title: 'Chimpanzee' },
  { slug: 'wolf', name_ko: '늑대', name_en: 'Wolf', wiki_title: 'Wolf' },
  { slug: 'brown-bear', name_ko: '갈색곰', name_en: 'Brown Bear', wiki_title: 'Brown_bear' },
  { slug: 'polar-bear', name_ko: '북극곰', name_en: 'Polar Bear', wiki_title: 'Polar_bear' },
  { slug: 'fox', name_ko: '여우', name_en: 'Fox', wiki_title: 'Red_fox' },
  { slug: 'deer', name_ko: '사슴', name_en: 'Deer', wiki_title: 'Deer' },
  { slug: 'kangaroo', name_ko: '캥거루', name_en: 'Kangaroo', wiki_title: 'Kangaroo' },
  { slug: 'koala', name_ko: '코알라', name_en: 'Koala', wiki_title: 'Koala' },
  { slug: 'giant-panda', name_ko: '판다', name_en: 'Giant Panda', wiki_title: 'Giant_panda' },
  { slug: 'camel', name_ko: '낙타', name_en: 'Camel', wiki_title: 'Camel' },
  { slug: 'jaguar', name_ko: '재규어', name_en: 'Jaguar', wiki_title: 'Jaguar' },
  { slug: 'hyena', name_ko: '하이에나', name_en: 'Hyena', wiki_title: 'Hyena' },
  { slug: 'meerkat', name_ko: '미어캣', name_en: 'Meerkat', wiki_title: 'Meerkat' },
  { slug: 'orangutan', name_ko: '오랑우탄', name_en: 'Orangutan', wiki_title: 'Orangutan' },
  { slug: 'raccoon', name_ko: '라쿤', name_en: 'Raccoon', wiki_title: 'Raccoon' },
  { slug: 'hedgehog', name_ko: '고슴도치', name_en: 'Hedgehog', wiki_title: 'Hedgehog' },
  { slug: 'bison', name_ko: '들소', name_en: 'Bison', wiki_title: 'American_bison' },
  { slug: 'wild-boar', name_ko: '멧돼지', name_en: 'Wild Boar', wiki_title: 'Wild_boar' },
  { slug: 'komodo-dragon', name_ko: '코모도왕도마뱀', name_en: 'Komodo Dragon', wiki_title: 'Komodo_dragon' },
  { slug: 'sloth', name_ko: '나무늘보', name_en: 'Sloth', wiki_title: 'Sloth' },
]
